version: "3.3"
services:
  netflix-app:
    image: netflix-app-krushna-jagdale
    container_name: "netflix-app"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    restart: always
